=== rfbaumgartner/mini-dietrich/original/kae.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
    <xs:element name='root'>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name='rand'>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name='kursiv'>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name='i'>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name='u'>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="pb">
        <xs:complexType>
            <xs:attribute name="n" type="xs:int" use="required" />
            <xs:attribute name="facs" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="lb">
        <xs:complexType>
            <xs:attribute name="n" type="xs:int" use="required" />
            <xs:attribute name="x" type="xs:int" use="required" />
            <xs:attribute name="y" type="xs:int" use="required" />
            <xs:attribute name="w" type="xs:int" use="required" />
            <xs:attribute name="h" type="xs:int" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="footnote">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="text" type="xs:string" use="required"/>
            <xs:attribute name="source" type="xs:string" use="optional"/>
            <xs:attribute name="link" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="titel">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="randtitel">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="marginalie">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="pag">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="paginierung">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="bleistiftpaginierung">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="abbreviation">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string" use="optional"/>
            <xs:attribute name="text" type="xs:string" use="optional"/>
            <xs:attribute name="value" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>


    <xs:element name="rs">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="person"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="key" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="subject">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"></xs:any>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string" use="required"/>
            <xs:attribute name="description" type="xs:string" use="optional"/>
            <xs:attribute name="loc" type="xs:string" use="optional"/>
            <xs:attribute name="date_when" type="xs:string" use="optional"/>
            <xs:attribute name="date_from" type="xs:string" use="optional"/>
            <xs:attribute name="date_to" type="xs:string" use="optional"/>
            <xs:attribute name="date_approx_when" type="xs:string" use="optional"/>
            <xs:attribute name="date_approx_from" type="xs:string" use="optional"/>
            <xs:attribute name="date_approx_to" type="xs:string" use="optional"/>
            <xs:attribute name="approx_when" type="xs:string" use="optional"/>
            <xs:attribute name="approx_from" type="xs:string" use="optional"/>
            <xs:attribute name="approx_to" type="xs:string" use="optional"/>
            <xs:attribute name="observation" type="xs:string" use="optional"/>
            <xs:attribute name="location" type="xs:string" use="optional"/>
            <xs:attribute name="quality" type="xs:int" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="foreign">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"></xs:any>
            </xs:sequence>
            <xs:attribute name="lang" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="lat|grie|it|fra, lat"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="trans_lang" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="de|lat"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="trans" type="xs:string" use="required"/>
            <xs:attribute name="source" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="date">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="when" type="xs:string" use="optional"/>
            <xs:attribute name="from" type="xs:string" use="optional"/>
            <xs:attribute name="to" type="xs:string" use="optional"/>
            <xs:attribute name="approx_when" type="xs:string" use="optional"/>
            <xs:attribute name="approx_from" type="xs:string" use="optional"/>
            <xs:attribute name="approx_to" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="interpunktionseingriff">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="type" type="xs:string" use="optional"/>
                    <xs:attribute name="comment" type="xs:string" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="texteingriff">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string" use="optional"/>
            <xs:attribute name="comment" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="del">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="textkriApp" type="xs:string" use="optional"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name='correction'>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string" use="required"/>
            <xs:attribute name="textkriApp" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="lesung">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"></xs:any>
            </xs:sequence>
            <xs:attribute name="text" type="xs:string" use="optional"/>
            <xs:attribute name="textkriApp" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="glossar">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="source" type="xs:string" use="required"/>
            <xs:attribute name="link" type="xs:string" use="optional"/>
            <xs:attribute name="text" type="xs:string" use="optional"/>
			
            <xs:attribute name="definition" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="gap">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string" use="optional"/>
            <xs:attribute name="textkriApp" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="todo">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"></xs:any>
            </xs:sequence>
            <xs:attribute name="comment" type="xs:string" use="required"/>
            <xs:attribute name="type" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="location">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="code" type="xs:string"  use="required"/>
            <xs:attribute name="link" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="table">
        <xs:complexType>
            <xs:all>
                <xs:element ref="tr" maxOccurs="unbounded"/>
                <xs:element ref="lb" minOccurs="0" maxOccurs="unbounded"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="tr">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="td" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="td">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="rowspan" type="xs:int" use="optional"/>
            <xs:attribute name="colspan" type="xs:int" use="optional"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="list">
        <xs:complexType>
            <xs:all>
                <xs:element ref="head" maxOccurs="unbounded"/>
                <xs:element ref="label" maxOccurs="unbounded"/>
                <xs:element ref="item" maxOccurs="unbounded"/>
                <xs:element ref="lb" minOccurs="0" maxOccurs="unbounded"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="head">
        <xs:complexType mixed="true">
            <xs:sequence>
               <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>    
        </xs:complexType>
    </xs:element>
    <xs:element name="label">
        <xs:complexType mixed="true"> 
           <xs:sequence>
               <xs:any minOccurs="0" maxOccurs="unbounded"/>
           </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="item">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="locations" type="xs:string"/>
</xs:schema>

=== rfbaumgartner/mini-dietrich/original/Mini-TEI_Dietrich_06_350.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kae.xsd">
    
<pb n="341" facs="KAE_A_HB_6-0350.jpg" />
<lb n="1" x="2" y="22" w="137" h="39" /><glossar source="Idiotikon (Bd. 2, Sp. 1363): abendlich, sich auf heutige Nacht beziehend.">mithinigen</glossar> Abendt- vnnd Extra Trünken dar-
<lb n="2" x="2" y="61" w="137" h="12" />auf gangen Ehrenwein  -- 19 Eÿm[er]. Darunder
<lb n="3" x="2" y="74" w="137" h="5" />ein Eymer Mesßwin
<lb n="4" x="2" y="79" w="137" h="11" />-- -- -- -- gemeiner Tisch-Wein 20 Eym[er]. -- -- --} 53
<lb n="5" x="2" y="91" w="137" h="7" />-- -- -- -- -- <kursiv>Communion</kursiv> Wein -- 14 Eÿm[er].
<lb n="6" x="2" y="98" w="137" h="17" /><foreign lang="lat" trans_lang="de" trans="insgesamt">Summa Sum[marum]</foreign> alles Weins,
<lb n="7" x="2" y="115" w="137" h="12" />so in der Engelw[eihe]. verbraucht
<lb n="8" x="2" y="127" w="137" h="18" />ist worden, ist -- -- -- 122 Eÿm[er]. 20 Mass.
<lb n="9" x="2" y="145" w="137" h="18" /><titel>An Mähl</titel>
<lb n="10" x="2" y="163" w="137" h="16" />Weisses verbachen 43 Mütt
<lb n="11" x="2" y="180" w="137" h="14" />-- -- schwarzes -- 73 Mütt
<lb n="12" x="2" y="194" w="137" h="6" />} 120 Mütt
<lb n="13" x="2" y="200" w="137" h="9" />-- -- in Kuchi geben 4 Mütt Weisß
<lb n="14" x="2" y="209" w="137" h="20" />Das Weissgebachen hatt geben, vnnd seÿnd ver-
<lb n="15" x="2" y="230" w="137" h="15" />braucht <glossar source="Idiotikon (Bd. 4, Sp. 604): kleiner Laib, Festbrötchen.">Mutschlin</glossar> 2860 paar.
<lb n="16" x="2" y="245" w="137" h="12" />-- -- Herren Brodt 2400 Brodt.
<lb n="17" x="2" y="257" w="137" h="15" />Schwarz Schirmer Brodt, seÿnd etwas
<lb n="18" x="2" y="272" w="137" h="13" />grösser als Knechtenbrodt seÿnd in obige gerechnet.
<lb n="19" x="2" y="285" w="137" h="15" />-- Knechtenbrodt 6924 Brodt.
<lb n="20" x="2" y="300" w="137" h="22" /><kursiv>Item</kursiv> an <glossar source="Idiotikon (Bd. 1, Sp. 348): Tierfett.">Vnschlitt</glossar> Kerzen wenigist 100 Pfund.
<lb n="21" x="2" y="323" w="137" h="13" />-- -- gesottnem Anken 600 Pf[und]
<lb n="22" x="2" y="336" w="137" h="7" />1165 Pf[und]
<lb n="23" x="2" y="343" w="137" h="12" />-- --frischem Anken -- -- -- 565 Pf[und]
<lb n="24" x="2" y="356" w="137" h="26" />Item an erkauften Fischen 895 ½ Pf[und]
<lb n="25" x="2" y="382" w="137" h="11" />-- -- -- -- -- 2888 Stuk <glossar source="Idiotikon (Bd. 2, Sp. 749): frisch (im Gegensatz zu 'dürr').">grüene</glossar> <glossar source="Idiotikon (Bd. 1, Sp. 185): Albek, Albich; Fischart.">Albelin</glossar>.
<lb n="26" x="2" y="393" w="137" h="18" />Item an Gflügel <glossar source="Kapaun; Kastrierter Masthahn.">Capaunen</glossar> 57 Stuk
<lb n="27" x="2" y="411" w="137" h="13" />-- an <glossar source="Brockhaus (Bd. 2, S. 969): Truthühner.">Welsche Hennen vnnd Hanen</glossar> 53 St[uk].
<lb n="28" x="2" y="425" w="137" h="13" />--Gänß -- -- -- -- 6  St[uk].
<lb n="29" x="2" y="438" w="137" h="52" />Parnisen
<lb n="1" x="143" y="386" w="137" h="-402" /><rand><bleistiftpaginierung value="[6_339]">[339]</bleistiftpaginierung>
<lb n="2" x="143" y="36" w="137" h="16" /><randtitel><foreign lang="lat" trans_lang="de" trans="Engelweihe">Ded[icatio] Angel[ica]</foreign></randtitel>
<lb n="3" x="143" y="52" w="137" h="47" /><randtitel><u>1687</u></randtitel></rand>
    
    
</root>
